apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: kong-zipkin
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  http_endpoint: http://{{ .Values.atscale.telemetry.fullnameOverride}}.{{ .Release.Namespace }}.svc.{{ .Values.atscale.global.clusterDomain }}:9411/api/v2/spans
  sample_ratio: 0.1
  include_credential: true
plugin: zipkin
