{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: minio
  namespace: {{ .Release.Namespace | default "atscale" }}
  labels:
    {{- include "atscale.labels" . | nindent 4 }}
  annotations:
    konghq.com/strip-path: "true"
  {{- with .Values.atscale.objectstorage.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: kong
  {{- if or (and .Values.global.atscale.tls.tlsCrt .Values.global.atscale.tls.tlsKey) .Values.global.atscale.tls.existingSecret }}
  tls:
  - secretName: {{ .Values.global.atscale.tls.existingSecret | default "default-certificate" }}
    hosts:
      - {{ .Values.global.ingressDomain }}
  {{- end }}
  rules:
  - host: {{ .Values.global.ingressDomain }}
    http:
      paths:
      - path: /minio
        pathType: ImplementationSpecific
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ .Values.atscale.objectstorage.fullnameOverride }}
            port:
              number: {{ .Values.atscale.objectstorage.service.ports.console }}
          {{- else }}
          serviceName: {{ .Values.atscale.objectstorage.fullnameOverride }}
          servicePort: {{ .Values.atscale.objectstorage.service.ports.console}}
          {{- end }}
---
